# Generated by Django 5.1.2 on 2024-10-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Siparis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YEMEK_ADI', models.CharField(max_length=100)),
                ('YEMEK_FIYATI', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ICECEK_ADI', models.CharField(max_length=100)),
                ('ICECEK_FIYATI', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ICECEK_ADEDI', models.PositiveIntegerField()),
                ('MUSTERI_ADI', models.CharField(max_length=100)),
                ('MASA_NUMARASI', models.PositiveIntegerField()),
                ('ODEME_METODU', models.CharField(choices=[('naqd', 'Nağd'), ('kart', 'Kartla')], max_length=10)),
                ('SIPARIS_TARIHI', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
