# Generated by Django 5.1.2 on 2024-10-26 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siparis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siparis',
            name='ICECEK_ADEDI',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='ICECEK_ADI',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='ICECEK_FIYATI',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='ODEME_METODU',
            field=models.CharField(choices=[('naqd', 'Nağd'), ('kart', 'Kartla')], default='naqd', max_length=10),
        ),
    ]
